### ISSUE TITLE
500 - An error has occurred - when opening PF migrator

### ISSUE THREAD

**Issue by shoulders** [projectknife/Migrator#1]
it appears to be referncing a table that does not exist. see image for full error.

i have installed joomla 2.5.11. i have removed any security apps that i had present for the migration and for the further upfgraded to j3.0

my error reporting in the global configuration of joomla was set to maximum (i was playing with it earlier). it also fails with this set to none.

i have checked the table does not exist.

earlier i upgraded a local copy of my site with no issues on xampp. it should of been an exact copy of my site (well about 1 month ago, but updated to latest joomla 2.5.11 prior to migration). but i am not 100% if it had this table or not.

i have never installed any of the PF3 pro extensions

![500](https://f.cloud.github.com/assets/319997/790041/ade4dae0-eb1e-11e2-9f7c-afd380ec9343.jpg)

**Comment by eaxs** [comment]
oh damn, I know why this is. I'll release a patch asap :)

**Comment by eaxs** [comment]
Alright, got it fixed. Please uninstall the migrator and then install the new version:
http://projectfork.net/downloads/projectfork-migrator/projectfork-migrator-1-0-1/compfmigrator1-0-1-zip?format=raw

Thanks!

**Comment by shoulders** [comment]
the migrator installed correctely and migrated my data. it all seems correct but i am having a heck of a time getting PF4 set so it looks like the demo pictures so i cannot 100% gurantee my feedback but it does look good. (i will keep playing and learning)

thanks for speedy fix
