### ISSUE TITLE
Error: Failed to Install Projectfork 4!

### ISSUE THREAD

**Issue by simjuande** [projectknife/Migrator#3]
![migration](https://f.cloud.github.com/assets/4609552/795487/d14681c2-ecfa-11e2-974a-8780248de3ff.jpg)

I uninstall PF3 Extension except those 2 in the documentation then i just update my Joomla 2.5.3 to 2.5.11 version, but when i used the PF3 to 4 Migrator Tools i got stock with this Error: Failed to Install Projectfork 4! anyone can help me?

Thanks in advance.

Sorry for my bad english.

**Comment by eaxs** [comment]
Hi there!

Unfortunately it does not really tell why it failed to install Projectfork. I'll have to update the migrator to include more details. What is clear through, is that failed at the actual installation. Meaning that the install package was found and properly extracted to the temporary directory.

How comes that the _tmp database tables already exist? was that the second time you ran the migration?

While I update the migrator to include more info about the actual cause of the error, you can try the following (I assume you have a backup):
- Open phpMyAdmin
- Delete all db tables starting with j25_pf_
- Go to: Your site backend > Extensions Manager > Install Projectfork 4 (Get the latest release)

This should tell you why it's not installing.

**Comment by simjuande** [comment]
yes i have a full back up  this  j25_pf_ this will come up when the migration process start.?

**Comment by eaxs** [comment]
I don't fully understand what you're asking. In step 1, all Projectfork tables are renamed to have a "_tmp" suffix at the end. When you run the migration for the first time, those tables should not yet exist.

Have you tried this yet:

> While I update the migrator to include more info about the actual cause of the error, you can try the following (I assume you have a backup):
> - Open phpMyAdmin
> - Delete all db tables starting with j25_pf_
> - Go to: Your site backend > Extensions Manager > Install Projectfork 4 (Get the latest release)

?

**Comment by simjuande** [comment]
While I update the migrator to include more info about the actual cause of the error, you can try the following (I assume you have a backup):

Open phpMyAdmin
Delete all db tables starting with j25_pf_
Go to: Your site backend > Extensions Manager > Install Projectfork 4 (Get the latest release)

![pf4](https://f.cloud.github.com/assets/4609552/810000/d71eb0e0-eea5-11e2-8abd-b1595935e0af.jpg)

Hi there Sir eaxs.
I successfully installed the PF4 when following your instruction, so whats the reason why ive got a PF4 Error Installing? before when im using the migration tool, i attemp in a second chance migration but before that i delete all the created "_tmp" i base my database structure here: http://3.projectfork.net/documentation/developers/database-table-structure.php

So the migration successfully rename the tables into "_tmp" but still im stocked in Error: Failed to Install Projectfork 4!

Please help me im a biggener :) tnx in advance

**Comment by simjuande** [comment]
By the way Sir eaxs i already figure why im getting those error, because when i try to use another DB its fine i got some error but conflict of data only, i think my DB was a lot crap when i try my first migration but overall it was successfully migrated tanx a lot... :100:
