### ISSUE TITLE
category was not retained after migration

### ISSUE THREAD

**Issue by valcaro87** [projectknife/Migrator#5]
categories was not retained. please help.thanks.
![categories was not retained](https://f.cloud.github.com/assets/5020577/803934/547ae43e-edff-11e2-8e58-66640bc617b7.png)

**Comment by eaxs** [comment]
You're right. We don't have this included in the migration.
I'll add it, thanks!

**Comment by eaxs** [comment]
Got it done. The update will be released later today.
