### ISSUE TITLE
13. Migrating Repository Folders - Duplicate entry

### ISSUE THREAD

**Issue by bembelimen** [projectknife/Migrator#6]
Hello,

the migration works till point 13. There I get the following error:

PFTableDirectory: :store failed<br />Duplicate entry '69' for key 'PRIMARY' SQL=INSERT INTO `jos_pf_repo_dirs` (`parent_id`,`level`,`lft`,`rgt`,`alias`,`project_id`,`title`,`description`,`created`,`created_by`,`attribs`,`access`,`protected`) VALUES ('463','3','39','40','xxxxxx','3','XXXXXX','','2013-07-17 11:04:07','763','{}','6','0')

The original entry (from the old tables) has an ID of 457.

**Comment by simjuande** [comment]
![pftables](https://f.cloud.github.com/assets/4609552/816533/d9bdc378-ef49-11e2-9164-417bff149472.jpg)

check my error there i just filter in my database for searching %Itamar Email Campaign% this data,  i found 2 tables that have the same data in "j25_pf_folders", "jos_pf_folders" so i just delete it.. and then i migrate again it smoothly finished. but before i got in number 13 process i encounter 4 duplicates... hope it helps

**Comment by bembelimen** [comment]
The problem is/was, that the migration component saves the directories first with the standard (auto increment) id and after updates the id to the old one (from projectfork 3). But the auto increment value will not be updated, so with enouth directories, there will be a conflict. Solution (as quickfix, I guess not very clean): admin/models/repodirs.php add in line 254:

```
    // Change the auto_increment value
    $this->_db->setQuery('ALTER TABLE #__pf_repo_dirs AUTO_INCREMENT =1');
    $this->_db->execute();
```

**Comment by eaxs** [comment]
> The problem is/was, that the migration component saves the directories first with the standard (auto increment) id and after updates the id to the old one (from projectfork 3). But the auto increment value will not be updated, so with enouth directories, there will be a conflict.

This observation is correct. However, I went a different way to solve the problem because the ALTER TABLE rebuilds the whole table - which is as you said not very clean. Instead, I'm taking the highest ID of the old table, insert it into the new one and then delete it again when the migration starts to artificially raise the auto_inc value.
