### ISSUE TITLE
15. Migrating Repository Files - Duplicate entry 'xxxxx' for key 'idx_alias'

### ISSUE THREAD

**Issue by bembelimen** [projectknife/Migrator#7]
Hello,

the problem is, that the old title (in version 3) can have up to 255 chars as title but in the new version (projectfork 4) the fields are limited to 56 chars.

So 1. every title and alias will be cut when saved to the database. 2. the dublicate alias check does not consider the field length, so every "long" alias is ok but breaks when the db cuts the string.

**Comment by eaxs** [comment]
You're right, thanks! I need to check if other areas are affected as well by this.
